<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9668" started-at="2019-02-19T14:19:33Z" finished-at="2019-02-19T14:19:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9668" started-at="2019-02-19T14:19:33Z" finished-at="2019-02-19T14:19:42Z">
      <class name="eSing_Java_TestNG_package.eSing_Java_TestNG_File">
        <test-method status="PASS" signature="a_test()[pri:0, instance:eSing_Java_TestNG_package.eSing_Java_TestNG_File@62ee68d8]" name="a_test" duration-ms="15" started-at="2019-02-19T14:19:33Z" finished-at="2019-02-19T14:19:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a_test -->
        <test-method status="PASS" signature="verifyHomePageTitle()[pri:0, instance:eSing_Java_TestNG_package.eSing_Java_TestNG_File@62ee68d8]" name="verifyHomePageTitle" duration-ms="9594" started-at="2019-02-19T14:19:33Z" finished-at="2019-02-19T14:19:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageTitle -->
        <test-method status="FAIL" signature="c_test()[pri:3, instance:eSing_Java_TestNG_package.eSing_Java_TestNG_File@62ee68d8]" name="c_test" duration-ms="3" started-at="2019-02-19T14:19:42Z" finished-at="2019-02-19T14:19:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at eSing_Java_TestNG_package.eSing_Java_TestNG_File.c_test(eSing_Java_TestNG_File.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c_test -->
        <test-method status="SKIP" signature="b_test()[pri:7, instance:eSing_Java_TestNG_package.eSing_Java_TestNG_File@62ee68d8]" name="b_test" duration-ms="3" started-at="2019-02-19T14:19:42Z" finished-at="2019-02-19T14:19:42Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping b_test...]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping b_test...
at eSing_Java_TestNG_package.eSing_Java_TestNG_File.b_test(eSing_Java_TestNG_File.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b_test -->
      </class> <!-- eSing_Java_TestNG_package.eSing_Java_TestNG_File -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
